export const ActionTypes = {
    FETCH_EMP: "FETCH_EMP",
    FETCH_EMP_ERROR: "FETCH_EMP_ERROR",
    UPDATE_EMP: "UPDATE_EMP",
    UPDATE_EMP_ERROR: "UPDATE_EMP_ERROR",
    DELETE_EMP: "DELETE_EMP",
    DELETE_EMP_ERROR: "DELETE_EMP_ERROR"
}